import type { CalculatorCatalogEntry } from '@/lib/calculators/types';

export const calculators = [
  {
    slug: 'maintenance-cost',
    category: 'car',
    route: '/car/maintenance-cost/',
    title: '자동차 유지비 계산기',
    description: '주행거리와 보험료, 세금, 정비비를 더해 연간·월간 자동차 유지비를 살펴봅니다.',
    lastReviewed: '2026-09-16',
    relatedSlugs: ['fuel-cost', 'ev-charging-cost', 'purchase-cost'],
    guide: {
      formula: '연간 유지비 = 에너지 비용 + 보험료 + 자동차세 + 정비·소모품비 + 주차·통행료 등 기타 비용',
      examples: [{ title: '내연기관 연간 계획', text: '연 12,000km, 연비 12km/L, 단가 1,700원/L이면 연료비는 170만원입니다. 보험료 80만원, 세금 30만원, 정비 40만원, 기타 60만원을 더하면 연 380만원입니다.' }, { title: '전기차 연간 계획', text: '연 12,000km, 전비 6km/kWh, 단가 300원/kWh이면 충전비는 60만원입니다. 나머지 비용이 연 180만원이면 월 평균 유지비는 20만원입니다.' }],
      limitations: ['감가상각, 대출 이자, 사고 수리비는 기본 계산에 포함하지 않습니다.', '보험료와 자동차세는 차량·운전자 조건에 따라 달라집니다.'],
      sources: [{ label: '국토교통부 자동차365', href: 'https://www.car365.go.kr/' }],
    },
  },
  {
    slug: 'fuel-cost',
    category: 'car',
    route: '/car/fuel-cost/',
    title: '유류비·연비 계산기',
    description: '주행거리, 연비, 유종 단가로 필요한 연료량과 예상 유류비를 계산합니다.',
    lastReviewed: '2026-09-16',
    relatedSlugs: ['maintenance-cost', 'purchase-cost'],
    guide: {
      formula: '예상 유류비 = 주행거리 ÷ 연비(km/L) × 유종 단가(원/L)',
      examples: [{ title: '주말 장거리 운전', text: '420km를 주행하고 연비가 14km/L, 유종 단가가 1,700원/L이면 30L가 필요하며 유류비는 51,000원입니다.' }, { title: '출퇴근 비용', text: '200km, 연비 10km/L, 단가 1,600원/L이면 20L를 사용하고 유류비는 32,000원입니다.' }],
      limitations: ['실제 연비는 교통량, 공회전, 적재량, 운전 습관에 따라 달라집니다.', '주유 할인과 유가 변동은 반영하지 않습니다.'],
      sources: [{ label: '한국석유공사 오피넷', href: 'https://www.opinet.co.kr/' }],
    },
  },
  {
    slug: 'ev-charging-cost',
    category: 'car',
    route: '/car/ev-charging-cost/',
    title: '전기차 충전비 계산기',
    description: '주행거리와 전비, 충전 단가를 기준으로 전력 사용량과 충전비를 추정합니다.',
    lastReviewed: '2026-09-16',
    relatedSlugs: ['maintenance-cost', 'fuel-cost'],
    guide: {
      formula: '예상 충전비 = 주행거리 ÷ 전비(km/kWh) × 충전 단가(원/kWh)',
      examples: [{ title: '월간 충전 계획', text: '240km를 주행하고 전비가 6km/kWh, 충전 단가가 300원/kWh이면 40kWh가 필요하며 충전비는 12,000원입니다.' }, { title: '급속 충전 단가 비교', text: '500km, 전비 5km/kWh, 충전 단가 400원/kWh이면 100kWh가 필요하며 충전비는 40,000원입니다.' }],
      limitations: ['충전 손실과 계절, 주행 습관 차이는 반영하지 않습니다.', '충전 사업자와 시간대별 요금은 직접 입력한 단가에만 반영됩니다.'],
      sources: [{ label: '환경부 무공해차 통합누리집', href: 'https://ev.or.kr/' }],
    },
  },
  {
    slug: 'purchase-cost',
    category: 'car',
    route: '/car/purchase-cost/',
    title: '차량 구매 총비용 계산기',
    description: '차량 가격과 선택 비용, 초기 현금, 할부 원금을 비교해 필요한 자금을 정리합니다.',
    lastReviewed: '2026-09-16',
    relatedSlugs: ['installment', 'maintenance-cost', 'loan-repayment'],
    guide: {
      formula: '자금 조달 차이 = 차량 가격 + 선택 비용 - 초기 현금 - 할부 원금',
      examples: [{ title: '구매 예산 점검', text: '차량 3,000만원과 선택 비용 200만원을 현금 1,200만원, 할부 2,000만원으로 조달하면 자금 차이는 0원입니다.' }, { title: '추가 자금 확인', text: '차량 3,000만원과 선택 비용 200만원에 현금 1,000만원, 할부 2,000만원을 입력하면 200만원이 더 필요합니다.' }],
      limitations: ['취득세, 보험료, 공채 등은 자동 추정하지 않습니다.', '할부는 원리금균등 가정을 사용하며 실제 계약 조건과 다를 수 있습니다.'],
      sources: [{ label: '국토교통부 자동차365', href: 'https://www.car365.go.kr/' }],
    },
  },
  {
    slug: 'installment',
    category: 'car',
    route: '/car/installment/',
    title: '자동차 할부 계산기',
    description: '할부 원금과 금리, 기간, 상환 방식에 따른 월 납입액과 총이자를 비교합니다.',
    lastReviewed: '2026-09-16',
    relatedSlugs: ['purchase-cost', 'loan-repayment', 'loan-interest'],
    guide: {
      formula: '원리금균등 월 납입액 = 원금 × 월 이자율 × (1 + 월 이자율)^개월 수 ÷ ((1 + 월 이자율)^개월 수 - 1)',
      examples: [{ title: '무이자 60개월', text: '할부 원금 3,000만원을 0% 금리로 60개월 원리금균등 상환하면 월 50만원이며 총이자는 0원입니다.' }, { title: '만기일시 12개월', text: '원금 1,200만원, 연 6%, 12개월 만기일시는 매월 이자 6만원을 내고 마지막 달에 원금 포함 1,206만원을 납입합니다.' }],
      limitations: ['취급 수수료, 중도상환 수수료, 연체 이자는 반영하지 않습니다.', '실제 금융 계약의 납입일과 원 단위 처리 방식은 다를 수 있습니다.'],
      sources: [{ label: '금융감독원 금융소비자정보포털 파인', href: 'https://fine.fss.or.kr/' }],
    },
  },
  {
    slug: 'loan-interest',
    category: 'finance',
    route: '/finance/loan-interest/',
    title: '대출 이자 계산기',
    description: '대출 원금, 연 이자율, 이용 기간으로 단리 기준 예상 이자와 만기 금액을 계산합니다.',
    lastReviewed: '2026-09-16',
    relatedSlugs: ['loan-repayment', 'installment'],
    guide: {
      formula: '단리 이자 = 대출 원금 × 연 이자율 × 이용 기간(연 단위)',
      examples: [{ title: '6개월 자금 이용', text: '원금 1,000만원, 연 6%, 6개월을 입력하면 단리 이자는 30만원, 원금 포함 만기액은 1,030만원입니다.' }, { title: '일 단위 이용', text: '원금 365만원, 연 10%, 10일, 연 기준 365일이면 단리 이자는 10,000원입니다. 366일 기준을 선택하면 결과가 달라집니다.' }],
      limitations: ['금융기관별 일수 계산 방식, 우대금리, 연체이자는 반영하지 않습니다.', '참고용 계산이며 실제 계약·청구 금액과 다를 수 있습니다.'],
      sources: [{ label: '금융감독원 금융소비자정보포털 파인', href: 'https://fine.fss.or.kr/' }],
    },
  },
  {
    slug: 'loan-repayment',
    category: 'finance',
    route: '/finance/loan-repayment/',
    title: '대출 상환 방식 비교 계산기',
    description: '원리금균등, 원금균등, 만기일시 상환의 월 납입액과 총이자를 비교합니다.',
    lastReviewed: '2026-09-16',
    relatedSlugs: ['loan-interest', 'compound-interest', 'installment'],
    guide: {
      formula: '월 이자율 = 연 이자율 ÷ 12, 원금균등은 매월 같은 원금에 남은 원금 이자를 더합니다.',
      examples: [{ title: '원금균등 12개월', text: '원금 1,200만원, 연 6%, 12개월 원금균등은 첫 달 106만원, 마지막 달 100만5천원이며 총이자는 39만원입니다.' }, { title: '만기일시와 비교', text: '같은 원금 1,200만원, 연 6%, 12개월 만기일시는 총이자가 72만원입니다. 원금을 늦게 갚으므로 원금균등보다 이자가 큽니다.' }],
      limitations: ['거치 기간, 중도상환, 수수료는 반영하지 않습니다.', '0% 금리는 원금을 개월 수로 나누는 단순 가정으로 계산합니다.'],
      sources: [{ label: '금융감독원 금융소비자정보포털 파인', href: 'https://fine.fss.or.kr/' }],
    },
  },
  {
    slug: 'compound-interest',
    category: 'finance',
    route: '/finance/compound-interest/',
    title: '예적금·복리 계산기',
    description: '초기 원금과 매월 납입액, 금리, 기간으로 만기 예상액과 이자를 계산합니다.',
    lastReviewed: '2026-09-16',
    relatedSlugs: ['loan-repayment', 'monthly-budget'],
    guide: {
      formula: '월 복리 · 매월 말 납입: 월말 잔액 = 전월 잔액 × (1 + 연 이자율 ÷ 100 ÷ 12) + 매월 납입액',
      examples: [{ title: '두 달 복리', text: '초기 원금 100만원, 연 12%, 매월 납입 0원으로 2개월이면 월 1% 이자가 누적되어 세전 만기액은 1,020,100원입니다.' }, { title: '매월 말 납입', text: '초기 원금 0원, 매월 말 10만원, 연 12%, 2개월이면 첫 납입액에 한 달 이자 1,000원이 붙어 세전 만기액은 201,000원입니다.' }],
      limitations: ['금융기관별 우대 조건, 중도해지, 이자 지급일은 반영하지 않습니다.', '세후 결과는 사용자가 직접 입력한 세율이 있을 때만 추정할 수 있습니다.'],
      sources: [{ label: '금융감독원 금융소비자정보포털 파인', href: 'https://fine.fss.or.kr/' }],
    },
  },
  {
    slug: 'monthly-budget',
    category: 'life',
    route: '/life/monthly-budget/',
    title: '월 생활비 예산 계산기',
    description: '월 순수입과 고정·변동 지출, 목표 저축액을 비교해 남는 금액을 정리합니다.',
    lastReviewed: '2026-09-16',
    relatedSlugs: ['maintenance-cost', 'compound-interest'],
    guide: {
      formula: '잔여 금액 = 월 순수입 - 고정비 - 변동비 - 목표 저축액',
      examples: [{ title: '월간 예산 점검', text: '월 순수입 300만원, 전체 지출 180만원, 목표 저축 70만원이면 잔여 금액은 50만원이고 지출 비율은 60%입니다.' }, { title: '지출이 큰 달', text: '월 순수입 200만원, 전체 지출 190만원, 목표 저축 30만원이면 잔여 금액은 -20만원입니다. 이 수치는 입력한 예산의 차이를 보여 줍니다.' }],
      limitations: ['개인의 재무 상태나 소비 습관을 평가하지 않습니다.', '자동차비는 자동차 유지비 계산기 결과를 직접 입력해야 합니다.'],
      sources: [{ label: '통계청 국가통계포털', href: 'https://kosis.kr/' }],
    },
  },
  {
    slug: 'take-home-pay',
    category: 'salary',
    route: '/salary/take-home-pay/',
    title: '연봉 실수령액 계산기',
    description: '수동으로 입력한 공제 요율·기준과 월 소득세를 바탕으로 월 예상 실수령액을 계산합니다.',
    lastReviewed: '2026-09-17',
    relatedSlugs: ['annual-leave-allowance', 'severance-pay'],
    guide: {
      formula: '월 예상 실수령액 = 연봉 ÷ 12 - (입력한 연금·건강·장기요양·고용보험·소득세·지방소득세 공제액)',
      examples: [{ title: '수동 공제 기준으로 월급 가늠', text: '연봉 3,600만원을 입력하고, 회사 급여명세서나 별도 확인 자료에 있는 공제 기준과 월 소득세를 직접 입력하면 그 가정에 따른 월 예상 실수령액을 확인할 수 있습니다.' }, { title: '비과세액을 포함한 급여', text: '연봉에 월 비과세 20만원이 포함되어 있다면 비과세액도 입력합니다. 이 계산기는 입력한 비과세액만 과세 대상 월급에서 빼며 실제 과세 판단은 하지 않습니다.' }],
      limitations: ['2026년 법정 요율·상한·간이세액표를 내장하지 않은 수동 설정 예상 계산입니다.', '보험 보수월액, 공제·감면, 상여, 연말정산과 회사의 원 단위 처리에 따라 실제 급여명세서와 다를 수 있습니다.'],
      sources: [{ label: '국세청 홈택스', href: 'https://www.hometax.go.kr/' }],
    },
  },
  {
    slug: 'hourly-monthly-pay',
    category: 'salary',
    route: '/salary/hourly-monthly-pay/',
    title: '시급·월급 계산기',
    description: '시급, 주 소정근로시간, 유급 주 수를 입력해 기본급과 주휴수당 가정의 월 급여를 계산합니다.',
    lastReviewed: '2026-09-17',
    relatedSlugs: ['weekly-holiday-pay', 'take-home-pay'],
    guide: {
      formula: '월 예상액 = 시급 × 주 소정근로시간 × 유급 주 수 + 계산된 주휴수당',
      examples: [{ title: '주 40시간, 4주', text: '시급 1만원, 주 40시간, 유급 4주를 입력하면 기본급 160만원과 주휴수당 32만원을 합쳐 192만원으로 계산합니다.' }, { title: '주 20시간, 4주', text: '시급 1만2천원, 주 20시간, 유급 4주를 입력하면 기본급 96만원과 주휴수당 19만2천원을 합쳐 115만2천원으로 계산합니다.' }],
      limitations: ['주휴수당은 5일·40시간 비교와 출근 요건 충족을 가정합니다.', '연장·야간·휴일 가산, 휴게시간, 실제 월력과 임금명세서의 반올림은 반영하지 않습니다.'],
      sources: [{ label: '국가법령정보센터 근로기준법', href: 'https://www.law.go.kr/' }],
    },
  },
  {
    slug: 'weekly-holiday-pay',
    category: 'salary',
    route: '/salary/weekly-holiday-pay/',
    title: '주휴수당 계산기',
    description: '시급과 4주 평균 주 소정근로시간, 요건을 충족한 주 수로 주휴수당을 추정합니다.',
    lastReviewed: '2026-09-17',
    relatedSlugs: ['hourly-monthly-pay', 'annual-leave-allowance'],
    guide: {
      formula: '주휴수당 = 시급 × min(주 소정근로시간, 40) ÷ 5 × 요건 충족 주 수',
      examples: [{ title: '주 40시간, 4주', text: '시급 1만원, 주 40시간, 요건 충족 4주면 주 8시간씩 총 32시간, 주휴수당은 32만원입니다.' }, { title: '주 14시간', text: '시급 1만원, 4주 평균 주 소정근로시간 14시간이면 이 계산의 15시간 기준에 미달해 주휴수당은 0원으로 표시됩니다.' }],
      limitations: ['4주 평균 주 소정근로시간과 출근 등 실제 요건을 사용자가 확인해야 합니다.', '5일·40시간 비교는 계산 가정이며 근로계약, 휴일 배치, 유급휴일 운영에 따라 실제 지급액이 다를 수 있습니다.'],
      sources: [{ label: '국가법령정보센터 근로기준법 제18조', href: 'https://www.law.go.kr/LSW/lsSideInfoP.do?lsiSeq=283457&joNo=0018&joBrNo=00&docCls=jo&urlMode=lsScJoRltInfoR' }],
    },
  },
  {
    slug: 'severance-pay',
    category: 'salary',
    route: '/salary/severance-pay/',
    title: '퇴직금 계산기',
    description: '1일 평균임금과 재직일수를 입력해 공식 계산식 기준의 퇴직금 예상액을 계산합니다.',
    lastReviewed: '2026-09-17',
    relatedSlugs: ['take-home-pay', 'annual-leave-allowance'],
    guide: {
      formula: '퇴직금 예상액 = 1일 평균임금 × 30 × 재직일수 ÷ 365',
      examples: [{ title: '2년 재직', text: '1일 평균임금 10만원, 재직일수 730일이면 퇴직금 예상액은 600만원입니다.' }, { title: '3년 반 재직', text: '1일 평균임금 12만원, 재직일수 1,277일이면 120,000 × 30 × 1,277 ÷ 365 = 12,595,068.49…원이므로 원 단위 반올림 시 12,595,068원입니다.' }],
      limitations: ['계속근로기간, 평균임금 산정기간, 중간정산 등 실제 퇴직금 지급 자격과 기준은 이 계산기가 판단하지 않습니다.', '통상임금이 평균임금보다 높을 때의 적용과 회사의 원 단위 처리 등으로 실제 금액과 다를 수 있습니다.'],
      sources: [{ label: '고용노동부 퇴직금 계산기', href: 'https://www.moel.go.kr/retirementpayCal.do' }],
    },
  },
  {
    slug: 'annual-leave-allowance',
    category: 'salary',
    route: '/salary/annual-leave-allowance/',
    title: '미사용 연차수당 계산기',
    description: '이미 확인한 미사용 유급 연차일수와 1일 통상임금으로 연차수당 예상액을 계산합니다.',
    lastReviewed: '2026-09-17',
    relatedSlugs: ['take-home-pay', 'severance-pay'],
    guide: {
      formula: '미사용 연차수당 예상액 = 미사용 지급 대상 연차일수 × 1일 통상임금',
      examples: [{ title: '미사용 10일', text: '지급 대상 미사용 연차 10일, 1일 통상임금 10만원이면 연차수당 예상액은 100만원입니다.' }, { title: '반일 단위 포함', text: '지급 대상 미사용 연차 3.5일, 1일 통상임금 12만원이면 예상액은 42만원입니다.' }],
      limitations: ['발생일수, 사용촉진, 소멸, 지급 대상 여부는 사용자가 먼저 확인해야 합니다.', '통상임금의 범위와 취업규칙·근로계약의 정산 기준에 따라 실제 지급액이 다를 수 있습니다.'],
      sources: [{ label: '국가법령정보센터 근로기준법', href: 'https://www.law.go.kr/' }],
    },
  },
  {
    slug: 'unemployment-benefit',
    category: 'salary',
    route: '/salary/unemployment-benefit/',
    title: '실업급여 계산기',
    description: '기초일액과 소정급여일수, 직접 입력한 일 상·하한으로 구직급여 시나리오를 계산합니다.',
    lastReviewed: '2026-09-17',
    relatedSlugs: ['parental-leave-benefit', 'take-home-pay'],
    guide: {
      formula: '1일 구직급여 예상액 = min(max(기초일액 × 60%, 입력 하한), 입력 상한), 총액 = 1일 예상액 × 입력 일수',
      examples: [{ title: '상한 이내인 경우', text: '기초일액 10만원, 일 하한 5만원, 일 상한 8만원, 소정급여일수 120일이면 1일 6만원, 총 720만원입니다.' }, { title: '상한이 적용되는 경우', text: '기초일액 20만원, 일 하한 5만원, 일 상한 8만원, 소정급여일수 120일이면 1일 8만원, 총 960만원입니다.' }],
      limitations: ['고용보험 가입기간, 이직 사유, 취업 가능 상태 등 실제 수급 자격은 별도로 확인해야 합니다.', '하한·상한과 소정급여일수는 자동 추정하지 않으며, 사용자가 확인한 기준을 직접 입력하는 예상 계산입니다.'],
      sources: [{ label: '국가법령정보센터 고용보험법 제46조', href: 'https://www.law.go.kr/LSW/lsSideInfoP.do?lsiSeq=283373&joNo=0046&joBrNo=00&docCls=jo&urlMode=lsScJoRltInfoR' }],
    },
  },
  {
    slug: 'parental-leave-benefit',
    category: 'salary',
    route: '/salary/parental-leave-benefit/',
    title: '육아휴직 급여 계산기',
    description: '월 통상임금과 직접 입력한 지급률·월 상한으로 동일 조건의 육아휴직 급여 시나리오를 계산합니다.',
    lastReviewed: '2026-09-17',
    relatedSlugs: ['unemployment-benefit', 'take-home-pay'],
    guide: {
      formula: '월 급여 시나리오 = min(월 통상임금 × 입력 지급률, 입력 월 상한), 총액 = 월 급여 × 개월 수',
      examples: [{ title: '상한 이내 시나리오', text: '월 통상임금 300만원, 지급률 50%, 월 상한 200만원, 3개월이면 월 150만원, 총 450만원입니다.' }, { title: '상한 적용 시나리오', text: '월 통상임금 500만원, 지급률 50%, 월 상한 200만원, 3개월이면 월 200만원, 총 600만원입니다.' }],
      limitations: ['이 페이지는 월별 차등·특례를 반영하지 않는 동일 지급률·상한의 평면 시나리오입니다.', '고용보험 피보험기간, 자녀·휴직 요건, 실제 월별 수급 자격과 기준은 별도로 확인해야 합니다.'],
      sources: [{ label: '고용24 육아휴직 급여 안내', href: 'https://www.work24.go.kr/' }],
    },
  },
  {
    slug: 'salary-negotiation',
    category: 'salary',
    route: '/salary/salary-negotiation/',
    title: '연봉 협상 계산기',
    description: '현재 연봉과 목표 연봉의 연간·월간 차이와 인상률을 비교합니다.',
    lastReviewed: '2026-09-17',
    relatedSlugs: ['take-home-pay', 'freelancer-withholding'],
    guide: {
      formula: '연봉 차이 = 목표 연봉 - 현재 연봉, 월 차이 = 연봉 차이 ÷ 12, 인상률 = 연봉 차이 ÷ 현재 연봉 × 100',
      examples: [{ title: '10% 인상 목표', text: '현재 연봉 4,000만원, 목표 연봉 4,400만원이면 연 400만원, 월 약 33만3천333원 차이이며 인상률은 10%입니다.' }, { title: '목표 연봉이 낮은 경우', text: '현재 연봉 5,000만원, 목표 연봉 4,800만원이면 연 -200만원, 월 약 -16만6천667원 차이로 표시됩니다.' }],
      limitations: ['보너스, 비과세 수당, 성과급, 근로시간과 복지 조건은 포함하지 않습니다.', '현재 연봉이 0원일 때 인상률은 비교할 기준이 없으므로 0%로 표시합니다.'],
      sources: [{ label: '고용노동부 임금 정보', href: 'https://www.moel.go.kr/' }],
    },
  },
  {
    slug: 'freelancer-withholding',
    category: 'salary',
    route: '/salary/freelancer-withholding/',
    title: '프리랜서 원천징수 계산기',
    description: '총 수입과 직접 입력한 경비·원천징수율로 경비 차감 시나리오의 수령액을 계산합니다.',
    lastReviewed: '2026-09-17',
    relatedSlugs: ['salary-negotiation', 'monthly-budget'],
    guide: {
      formula: '원천징수 대상 시나리오 = max(총 수입 - 입력 경비, 0), 원천징수 = 대상 × 입력 세율, 수령액 = 총 수입 - 원천징수',
      examples: [{ title: '경비를 반영한 시나리오', text: '총 수입 100만원, 경비 20만원, 원천징수율 3%이면 대상 80만원, 원천징수 2만4천원, 수령액 97만6천원입니다.' }, { title: '경비가 수입보다 큰 경우', text: '총 수입 50만원, 경비 60만원, 원천징수율 3%이면 대상과 원천징수는 0원, 수령액은 50만원입니다.' }],
      limitations: ['이 계산기는 경비 차감 후 세율을 적용하는 시나리오이며 법정 사업소득 원천징수 판정을 대신하지 않습니다.', '부가가치세와 마진은 별도 계산기에서 매출·매입 및 비용 구조를 확인해야 하며, 수령액은 경비를 뺀 이익이 아닙니다.'],
      sources: [{ label: '국세청', href: 'https://www.nts.go.kr/' }],
    },
  },
  {
    slug: 'savings-maturity',
    category: 'finance',
    route: '/finance/savings-maturity/',
    title: '적금 만기 계산기',
    description: '매월 말 납입액과 연 이자율, 직접 입력한 세율로 월 복리 적금의 만기 예상액을 계산합니다.',
    lastReviewed: '2026-09-17',
    relatedSlugs: ['deposit-interest', 'compound-interest', 'monthly-budget'],
    guide: {
      formula: '월말 잔액 = 전월 잔액 × (1 + 연 이자율 ÷ 100 ÷ 12) + 월 납입액, 세금 = 총이자 × 입력 세율 ÷ 100',
      examples: [{ title: '월말 납입 복리 예시', text: '월 10만원, 연 12%, 2개월, 세율 10%를 가정하면 원금 20만원, 세전 이자 1,000원, 세후 만기액 20만900원입니다.' }, { title: '무이자 저축 예시', text: '월 20만원, 연 0%, 12개월, 입력 세율 0%이면 총 납입원금과 만기액은 모두 240만원입니다.' }],
      limitations: ['매월 말 납입·월 복리를 가정하므로 일반 단리 적금이나 실제 납입일 기준 상품과 결과가 다릅니다.', '세율은 예시나 법정값을 자동 적용하지 않습니다. 본인 상품의 과세 조건을 확인해 직접 입력하세요.', '중도해지, 우대금리, 월별 납입 누락과 금융기관의 절사 방식은 반영하지 않습니다.'],
      sources: [{ label: '금융감독원 금융상품한눈에 · 실제 상품 조건 확인', href: 'https://finlife.fss.or.kr/' }],
    },
  },
  {
    slug: 'deposit-interest',
    category: 'finance',
    route: '/finance/deposit-interest/',
    title: '예금 이자 계산기',
    description: '예치 원금과 연 이자율, 기간, 직접 입력한 세율을 바탕으로 단리 예금의 세전·세후 이자를 계산합니다.',
    lastReviewed: '2026-09-17',
    relatedSlugs: ['savings-maturity', 'compound-interest', 'loan-interest'],
    guide: {
      formula: '세전 이자 = 원금 × 연 이자율 ÷ 100 × 개월 수 ÷ 12, 세후 만기액 = 원금 + 세전 이자 × (1 - 입력 세율 ÷ 100)',
      examples: [{ title: '1년 단리 예시', text: '원금 100만원, 연 6%, 12개월, 세율 10%를 가정하면 세전 이자 6만원, 세금 6,000원, 세후 만기액 105만4,000원입니다.' }, { title: '반년 예치 예시', text: '원금 200만원, 연 3%, 6개월, 입력 세율 0%를 가정하면 이자 3만원, 만기액 203만원입니다.' }],
      limitations: ['세율은 수동 입력값이며 예시의 세율이 법정 세율이나 실제 상품 조건을 뜻하지 않습니다.', '단리·개월 수 기준 계산입니다. 일수 기준, 복리 상품, 중도해지와 우대 조건은 별도 확인하세요.'],
      sources: [{ label: '금융감독원 금융상품한눈에 · 예금 조건 확인', href: 'https://finlife.fss.or.kr/' }],
    },
  },
  {
    slug: 'loan-affordability',
    category: 'finance',
    route: '/finance/loan-affordability/',
    title: '대출 상환 여력 계산기',
    description: '월 순수입과 기존 상환액, 직접 정한 상환 비율로 감당 가능한 월 납입액과 원리금균등 대출 원금을 추정합니다.',
    lastReviewed: '2026-09-17',
    relatedSlugs: ['loan-repayment', 'dsr', 'monthly-budget'],
    guide: {
      formula: '월 상환 여력 A = max(월 순수입 × 입력 허용비율 ÷ 100 - 기존 월 상환액, 0). 월 이율 r, 기간 n일 때 추정 원금 = A × ((1+r)^n - 1) ÷ (r × (1+r)^n), 무이자는 A × n',
      examples: [{ title: '무이자 상환 계획', text: '월 순수입 300만원, 기존 월 상환액 20만원, 스스로 정한 허용비율 20%이면 월 여력은 40만원입니다. 연 0%, 12개월이면 추정 원금은 480만원입니다.' }, { title: '기존 상환액이 큰 경우', text: '월 순수입 200만원, 기존 월 상환액 60만원, 허용비율 20%이면 기준 40만원을 초과하므로 추가 상환 여력과 추정 원금은 0원입니다.' }],
      limitations: ['허용비율은 사용자가 정하는 예산 기준이며 법정 DSR·DTI 한도가 아닙니다.', '대출 승인·한도를 예측하지 않습니다. 신용, 담보, 심사 정책과 실제 생활비는 별도로 확인해야 합니다.', '고정금리 원리금균등을 가정하며 수수료, 거치기간과 금리 변동은 포함하지 않습니다.'],
      sources: [{ label: '금융감독원 금융소비자정보포털 파인 · 대출 정보 확인', href: 'https://fine.fss.or.kr/' }],
    },
  },
  {
    slug: 'dsr',
    category: 'finance',
    route: '/finance/dsr/',
    title: 'DSR 비율 계산기',
    description: '직접 입력한 연 소득과 연간 총 원리금 상환액의 비율을 계산합니다. 대출 승인 여부를 예측하지 않습니다.',
    lastReviewed: '2026-09-17',
    relatedSlugs: ['dti', 'ltv', 'loan-affordability'],
    guide: {
      formula: '입력 기준 DSR = 연간 총 원리금 상환액 ÷ 연 소득 × 100',
      examples: [{ title: '연 상환액 1,200만원', text: '연 소득 6,000만원, 연간 총 원리금 상환액 1,200만원이면 입력 기준 DSR은 20%입니다.' }, { title: '연 상환액 2,000만원', text: '연 소득 5,000만원, 연간 총 원리금 상환액 2,000만원이면 비율은 40%입니다. 이 수치는 승인 가능성을 뜻하지 않습니다.' }],
      limitations: ['입력값의 단순 비율로, 스트레스 금리·상품별 산정 만기·규제 제외 대출을 자동 판단하지 않습니다.', '연 소득이 0원이면 유효한 비율을 계산할 수 없어 편의상 0%로 표시합니다.', '대출 승인이나 규제 충족 여부를 판정하지 않습니다. 금융기관의 최신 산정 기준을 확인하세요.'],
      sources: [{ label: '금융위원회 · 대출 규제 및 정책 확인', href: 'https://www.fsc.go.kr/' }],
    },
  },
  {
    slug: 'dti',
    category: 'finance',
    route: '/finance/dti/',
    title: 'DTI 단순 비율 계산기',
    description: '연 소득 대비 입력한 주택부채 연간 상환액의 단순 비율을 계산합니다. 공식 DTI 심사나 대출 승인을 예측하지 않습니다.',
    lastReviewed: '2026-09-17',
    relatedSlugs: ['dsr', 'ltv', 'loan-affordability'],
    guide: {
      formula: '이 페이지의 단순 비율 = 입력한 주택부채 연간 상환액 ÷ 연 소득 × 100',
      examples: [{ title: '주택부채 연 상환액 900만원', text: '연 소득 6,000만원, 주택부채 연간 상환액 900만원이면 단순 비율은 15%입니다.' }, { title: '주택부채 연 상환액 1,200만원', text: '연 소득 4,000만원, 주택부채 연간 상환액 1,200만원이면 단순 비율은 30%이며 공식 심사 결과가 아닙니다.' }],
      limitations: ['주택부채 상환액만 사용하는 단순 모델로 기타 대출 이자 등을 포함하는 실제 DTI 산정과 다를 수 있습니다.', '연 소득이 0원이면 유효한 비율을 계산할 수 없어 편의상 0%로 표시합니다.', '대출 승인·한도나 규제 충족을 판단하지 않습니다. 금융기관의 적용 항목을 별도 확인하세요.'],
      sources: [{ label: '금융위원회 · 주택담보대출 정책 확인', href: 'https://www.fsc.go.kr/' }],
    },
  },
  {
    slug: 'ltv',
    category: 'finance',
    route: '/finance/ltv/',
    title: 'LTV 비율 계산기',
    description: '입력한 담보 가치 대비 대출 금액의 비율을 계산합니다. 지역별 규제나 대출 승인 여부를 예측하지 않습니다.',
    lastReviewed: '2026-09-17',
    relatedSlugs: ['dsr', 'dti', 'loan-affordability'],
    guide: {
      formula: '입력 기준 LTV = 대출 금액 ÷ 담보 가치 × 100',
      examples: [{ title: '담보 가치 5억원', text: '담보 가치 5억원, 대출 금액 3억원이면 입력 기준 LTV는 60%입니다.' }, { title: '담보 가치 4억원', text: '담보 가치 4억원, 대출 금액 1억원이면 비율은 25%입니다. 실제 대출 가능 금액은 심사 결과에 따라 다릅니다.' }],
      limitations: ['담보 가치가 0원이면 유효한 비율을 계산할 수 없어 편의상 0%로 표시합니다.', '지역·주택 수·차주 조건별 규제, 선순위 채권, 임차보증금과 담보 평가 조정을 반영하지 않습니다.', '대출 승인이나 규제 충족 여부를 판단하는 계산기가 아닙니다.'],
      sources: [{ label: '금융위원회 · LTV 관련 정책 확인', href: 'https://www.fsc.go.kr/' }],
    },
  },
  {
    slug: 'card-instalment',
    category: 'finance',
    route: '/finance/card-instalment/',
    title: '카드 할부 계획 계산기',
    description: '구매 원금과 직접 입력한 연 이자율·기간으로 원리금균등 할부의 월별 납입 계획을 계산합니다.',
    lastReviewed: '2026-09-17',
    relatedSlugs: ['loan-repayment', 'loan-interest', 'monthly-budget'],
    guide: {
      formula: '월 납입액 = 원금 × 월 이율 × (1+월 이율)^개월 수 ÷ ((1+월 이율)^개월 수 - 1), 무이자는 원금 ÷ 개월 수',
      examples: [{ title: '12개월 무이자 계획', text: '원금 120만원, 연 이자율 0%, 12개월이면 매월 10만원, 총 납입액 120만원입니다.' }, { title: '1개월 이자 계획', text: '원금 100만원, 연 이자율 12%, 1개월이면 이자 1만원, 납입액 101만원입니다. 입력 이자율은 계산 예시입니다.' }],
      limitations: ['기존 원리금균등 상환 공식을 사용한 계획표입니다. 카드사의 원금균등·일수별 수수료 청구와 다를 수 있습니다.', '실제 카드 수수료율·무이자 혜택·부분 무이자·청구일 조정을 자동 조회하거나 적용하지 않습니다.'],
      sources: [{ label: '여신금융협회 · 카드 수수료 및 상품 정보 확인', href: 'https://www.crefia.or.kr/' }],
    },
  },
  {
    slug: 'manual-exchange-rate',
    category: 'finance',
    route: '/finance/manual-exchange-rate/',
    title: '수동 환율 계산기',
    description: '외화 금액과 직접 입력한 외화 1단위당 원화 환율로 환산합니다. 실시간 환율이 아닙니다.',
    lastReviewed: '2026-09-17',
    relatedSlugs: ['monthly-budget', 'deposit-interest'],
    guide: {
      formula: '원화 환산액 = 외화 금액 × 직접 입력한 외화 1단위당 원화 환율',
      examples: [{ title: '수동 환율 1,300원 예시', text: '외화 100단위, 수동 환율 1단위당 1,300원이면 원화 환산액은 13만원입니다. 실시간 환율이 아닙니다.' }, { title: '소수 단위 환산 예시', text: '외화 100.5단위, 수동 환율 1단위당 1,000원이면 원화 환산액은 10만500원입니다. 실시간 환율이 아닙니다.' }],
      limitations: ['실시간 환율이 아닙니다. 환율을 자동 조회·갱신하지 않으므로 원하는 시점과 거래 종류의 환율을 직접 확인해야 합니다.', '100엔 등 여러 단위 기준의 고시 환율은 외화 1단위당 원화 값으로 바꿔 입력하세요.', '환전 수수료, 매수·매도 차이, 우대율과 송금 비용은 포함하지 않습니다. 원화 결과는 원 단위로 반올림합니다.'],
      sources: [{ label: '한국은행 경제통계시스템 · 환율 참고 자료(자동 연동 없음)', href: 'https://ecos.bok.or.kr/' }],
    },
  },
  {
    slug: 'acquisition-tax', category: 'realestate', route: '/realestate/acquisition-tax/',
    title: '취득세 계산기', description: '취득 금액과 직접 확인한 세율로 단순 취득세 예상액을 계산합니다.', lastReviewed: '2026-09-17', relatedSlugs: ['brokerage-fee', 'housing-affordability'],
    guide: {
      formula: '예상 취득세 = 취득 금액 × 입력 세율 ÷ 100',
      examples: [{ title: '임의 세율 2% 시나리오', text: '취득 금액 1억원, 직접 입력한 세율 2%이면 예상액은 200만원입니다. 법정 적용 세율을 뜻하지 않습니다.' }, { title: '임의 세율 1% 시나리오', text: '취득 금액 2억원에 세율 1%를 입력하면 200만원입니다. 실제 적용 세율은 별도로 확인하세요.' }],
      limitations: ['입력 세율만 적용한 예상값이며 법정 취득세를 판정하지 않습니다.', '지역·주택 수·중과·감면·부가 세목과 과세표준 차이는 자동 반영하지 않습니다.'],
      sources: [{ label: '위택스 · 적용 세율과 세목 별도 확인', href: 'https://www.wetax.go.kr/' }],
    },
  },
  {
    slug: 'brokerage-fee', category: 'realestate', route: '/realestate/brokerage-fee/',
    title: '중개보수 계산기', description: '거래 금액과 수동 요율·상한으로 중개보수 예상액을 계산합니다.', lastReviewed: '2026-09-17', relatedSlugs: ['acquisition-tax', 'moving-budget'],
    guide: {
      formula: '예상 보수 = 거래 금액 × 입력 요율 ÷ 100과 입력 상한 중 작은 값',
      examples: [{ title: '입력 상한 적용', text: '거래 금액 1억원, 임의 요율 1%, 상한 30만원이면 결과는 30만원입니다.' }, { title: '요율 금액 적용', text: '거래 금액 1억원, 임의 요율 0.2%, 상한 50만원이면 결과는 20만원입니다.' }],
      limitations: ['법정 요율표를 내장하지 않은 예상값입니다. 계약 유형과 지역에 맞는 요율·상한을 직접 확인하세요.', '상한 0원은 보수 0원으로 계산합니다. 부가세·협의 할인·월세 거래금액 환산은 포함하지 않습니다.'],
      sources: [{ label: '국가법령정보센터 · 공인중개사법 및 지역 조례 확인', href: 'https://www.law.go.kr/' }],
    },
  },
  {
    slug: 'deposit-rent-conversion', category: 'realestate', route: '/realestate/deposit-rent-conversion/',
    title: '전월세 전환 계산기', description: '전환 대상 보증금과 직접 입력한 연 전환율로 기간 임대료를 추정합니다.', lastReviewed: '2026-09-17', relatedSlugs: ['rent-vs-deposit', 'rental-yield'],
    guide: {
      formula: '기간 환산 임대료 = 보증금 × 연 전환율 ÷ 100 × 개월 수 ÷ 12',
      examples: [{ title: '한 달 환산', text: '보증금 1억2천만원, 임의 연 전환율 4%, 1개월이면 40만원입니다.' }, { title: '세 달 환산', text: '같은 보증금과 전환율로 3개월을 입력하면 기간 합계는 120만원입니다.' }],
      limitations: ['수동 전환율로 산출한 예상값이며 법정 전환율 상한이나 계약 적법성을 판단하지 않습니다.', '전체 보증금 대신 실제 전환하려는 차액을 입력하세요. 복리·세금은 제외합니다.'],
      sources: [{ label: '국가법령정보센터 · 주택임대차보호법 확인', href: 'https://www.law.go.kr/' }],
    },
  },
  {
    slug: 'rent-vs-deposit', category: 'realestate', route: '/realestate/rent-vs-deposit/',
    title: '전세·월세 비교 계산기', description: '보증금의 기회비용과 월세를 합산해 각 계약의 월 환산 비용을 비교합니다.', lastReviewed: '2026-09-17', relatedSlugs: ['deposit-rent-conversion', 'monthly-budget'],
    guide: {
      formula: '월 환산 비용 = 월세 + 보증금 × 입력 연 기회비용률 ÷ 100 ÷ 12',
      examples: [{ title: '전세 조건', text: '보증금 1억2천만원, 월세 0원, 연 기회비용률 4%이면 월 환산 비용은 40만원입니다.' }, { title: '월세 조건 비교', text: '보증금 6천만원, 월세 30만원, 같은 4%이면 월 환산 비용은 50만원으로 앞 조건보다 10만원 큽니다.' }],
      limitations: ['각 계약 조건을 차례로 입력해 비교하는 예상값입니다. 기회비용은 실제 월 청구액이 아닙니다.', '대출 구조·보증금 반환 위험·관리비·세금·가격 변동은 반영하지 않습니다.'],
      sources: [{ label: '금융감독원 파인 · 금융 비용 확인', href: 'https://fine.fss.or.kr/' }],
    },
  },
  {
    slug: 'moving-budget', category: 'realestate', route: '/realestate/moving-budget/',
    title: '이사 비용 계산기', description: '이사·청소·중개보수와 기타 지출을 합산해 예상 예산을 정리합니다.', lastReviewed: '2026-09-17', relatedSlugs: ['brokerage-fee', 'one-person-setup-budget'],
    guide: {
      formula: '이사 예산 = 이사비 + 청소비 + 중개보수 + 기타 비용',
      examples: [{ title: '견적 합산', text: '이사비 50만원, 청소비 20만원, 중개보수 30만원, 기타 10만원이면 총 110만원입니다.' }, { title: '직접 이사', text: '운송 10만원과 기타 5만원, 나머지 0원이면 총 15만원입니다.' }],
      limitations: ['직접 입력한 견적 합계인 예상값이며 시세를 조회하지 않습니다.', '보증금·가구·가전 등 입력하지 않은 항목은 제외됩니다. 기타 비용에 중복 합산하지 마세요.'],
      sources: [{ label: '한국소비자원 · 이사 서비스 계약 참고', href: 'https://www.kca.go.kr/' }],
    },
  },
  {
    slug: 'one-person-setup-budget', category: 'realestate', route: '/realestate/one-person-setup-budget/',
    title: '자취 초기비용 계산기', description: '가구·가전·생활용품과 기타 준비 비용으로 자취 초기 예산을 계산합니다.', lastReviewed: '2026-09-17', relatedSlugs: ['moving-budget', 'monthly-budget'],
    guide: {
      formula: '초기 준비 예산 = 가구 + 가전 + 생활용품 + 기타 비용',
      examples: [{ title: '새 살림 마련', text: '가구 30만원, 가전 50만원, 생활용품 10만원, 기타 10만원이면 총 100만원입니다.' }, { title: '옵션 주택 입주', text: '가구·가전 0원, 생활용품 10만원, 기타 5만원이면 총 15만원입니다.' }],
      limitations: ['구매 계획을 더한 예상값으로 실제 판매 가격·배송비를 자동 조회하지 않습니다.', '보증금·월세·이사비는 별도 예산입니다. 필요하면 기타 비용에 직접 포함하세요.'],
      sources: [{ label: '한국소비자원 · 소비 지출 참고', href: 'https://www.kca.go.kr/' }],
    },
  },
  {
    slug: 'housing-affordability', category: 'realestate', route: '/realestate/housing-affordability/',
    title: '주택 구매 여력 계산기', description: '가용 현금, 수동 상환비율·금리·대출한도로 감당 가능한 주택 예산을 추정합니다.', lastReviewed: '2026-09-17', relatedSlugs: ['loan-affordability', 'acquisition-tax', 'holding-cost-checklist'],
    guide: {
      formula: '주택 예산 = 가용 현금 + min(월 상환 여력을 원리금균등으로 환산한 원금, 직접 입력한 대출한도)',
      examples: [{ title: '입력 한도 적용', text: '현금 1천만원, 월소득 300만원, 기존 상환 20만원, 허용비율 20%, 금리 0%, 12개월이면 원금 여력은 480만원입니다. 한도 400만원이면 주택 예산은 1,400만원입니다.' }, { title: '상환 여력 적용', text: '같은 조건에서 한도만 900만원으로 입력하면 여력 480만원을 적용해 주택 예산은 1,480만원입니다.' }],
      limitations: ['입력 비율·금리·한도에 따른 예상값이며 대출 승인·법정 DSR·LTV·지역 규제를 예측하지 않습니다.', '가용 현금은 취득세·중개보수·비상자금을 별도로 제외한 금액을 입력하세요. 고정금리 원리금균등을 가정합니다.', '기존 상환이 허용 예산 이상이면 추가 대출 여력을 0원으로 처리합니다.'],
      sources: [{ label: '금융감독원 파인 · 대출 계약 조건 별도 확인', href: 'https://fine.fss.or.kr/' }],
    },
  },
  {
    slug: 'rental-yield', category: 'realestate', route: '/realestate/rental-yield/',
    title: '임대 수익률 계산기', description: '연 임대료에서 입력 비용을 뺀 금액을 매입가와 비교해 수익률을 추정합니다.', lastReviewed: '2026-09-17', relatedSlugs: ['holding-cost-checklist', 'deposit-rent-conversion'],
    guide: {
      formula: '수익률 = max(연 임대료 − 연 비용, 0) ÷ 매입가 × 100',
      examples: [{ title: '양의 임대수익', text: '매입가 1억원, 연 임대료 1,200만원, 연 비용 200만원이면 수익률은 10%입니다.' }, { title: '비용이 더 큰 경우', text: '연 임대료 500만원, 연 비용 600만원이면 손실률 대신 0%를 표시합니다.' }],
      limitations: ['순임대료를 0원 아래로 내리지 않는 예상 지표로 손실률을 나타내지 않습니다. 매입가 0원도 편의상 0%로 표시합니다.', '시세차익·보증금·차입금·취득 부대비용은 자동 반영하지 않습니다.'],
      sources: [{ label: '한국부동산원 · 임대시장 자료 참고', href: 'https://www.reb.or.kr/' }],
    },
  },
  {
    slug: 'holding-cost-checklist', category: 'realestate', route: '/realestate/holding-cost-checklist/',
    title: '주택 보유비용 체크리스트', description: '직접 확인한 연간 세금·보험·관리·이자·기타 비용을 합산합니다.', lastReviewed: '2026-09-17', relatedSlugs: ['rental-yield', 'housing-affordability'],
    guide: {
      formula: '연간 보유비 = 연 세금 + 연 보험료 + 연 관리·수선비 + 연 이자 + 연 기타 비용',
      examples: [{ title: '연간 지출 정리', text: '세금 10만원, 보험 20만원, 관리 30만원, 이자 40만원, 기타 50만원이면 연 150만원입니다.' }, { title: '대출 없는 주택', text: '세금 30만원, 보험 10만원, 관리 80만원, 이자·기타 0원이면 연 120만원입니다.' }],
      limitations: ['고지서·견적에서 직접 입력한 연간 비용의 예상 합계입니다. 지역별 재산세·종부세를 예측하지 않습니다.', '월 지출은 12개월분으로 환산해 입력하세요. 원금 상환·감가상각·거래 비용은 별도입니다.'],
      sources: [{ label: '위택스 · 실제 지방세 고지 내역 확인', href: 'https://www.wetax.go.kr/' }],
    },
  },
  {
    slug: 'vat', category: 'business', route: '/business/vat/', title: '부가세 계산기',
    description: '직접 입력한 세율로 부가세 포함·별도 금액을 나눠 계산합니다.', lastReviewed: '2026-09-17', relatedSlugs: ['margin', 'online-market-settlement'],
    guide: {
      formula: '별도: 부가세 = 공급가 × 세율 ÷ 100 / 포함: 공급가 = 합계 ÷ (1 + 세율 ÷ 100)',
      examples: [{ title: '별도 금액', text: '공급가 10만원, 임의 세율 10%이면 부가세 1만원, 합계 11만원입니다.' }, { title: '포함 금액', text: '합계 11만원, 같은 10%로 포함 계산하면 공급가 10만원과 부가세 1만원으로 나뉩니다.' }],
      limitations: ['입력 세율을 적용한 예상값입니다. 면세·영세율·간이과세·매입세액 공제·실제 납부세액은 판단하지 않습니다.', '세율은 직접 확인해 입력하며 각 표시 금액은 원 단위로 반올림합니다.'],
      sources: [{ label: '국세청 · 부가가치세 안내', href: 'https://www.nts.go.kr/' }],
    },
  },
  {
    slug: 'margin', category: 'business', route: '/business/margin/', title: '마진율 계산기',
    description: '매출에서 원가를 뺀 이익과 매출 기준 마진율을 계산합니다.', lastReviewed: '2026-09-17', relatedSlugs: ['markup', 'break-even'],
    guide: {
      formula: '마진율 = (매출 − 원가) ÷ 매출 × 100',
      examples: [{ title: '이익 발생', text: '매출 10만원, 원가 8만원이면 이익 2만원, 마진율 20%입니다.' }, { title: '손실 발생', text: '매출 10만원, 원가 12만원이면 이익 −2만원, 마진율 −20%입니다.' }],
      limitations: ['입력 비용만 반영한 예상 지표로 순이익률과 다를 수 있습니다.', '매출 0원은 비율을 계산할 수 없어 편의상 0%로 표시합니다. 부가세 포함 여부를 통일하세요.'],
      sources: [{ label: 'OpenStax 재무회계 · 재무제표 비율 분석', href: 'https://openstax.org/books/principles-financial-accounting/pages/14-1-financial-statement-analysis' }],
    },
  },
  {
    slug: 'markup', category: 'business', route: '/business/markup/', title: '원가 가산율 계산기',
    description: '판매 이익을 원가로 나눠 원가 대비 가산율을 계산합니다.', lastReviewed: '2026-09-17', relatedSlugs: ['margin', 'discount-rate'],
    guide: {
      formula: '원가 가산율 = (매출 − 원가) ÷ 원가 × 100',
      examples: [{ title: '25% 가산', text: '매출 10만원, 원가 8만원이면 이익 2만원, 가산율 25%입니다.' }, { title: '원가 이하 판매', text: '매출 8만원, 원가 10만원이면 가산율은 −20%입니다.' }],
      limitations: ['입력 원가 기준 예상 지표이며 매출을 분모로 쓰는 마진율과 다릅니다.', '원가 0원은 비율을 계산할 수 없어 편의상 0%로 표시합니다. 세금·고정비는 입력 원가에 포함한 만큼만 반영됩니다.'],
      sources: [{ label: 'OpenStax 관리회계 · 비용과 가격 의사결정', href: 'https://openstax.org/details/books/principles-managerial-accounting' }],
    },
  },
  {
    slug: 'break-even', category: 'business', route: '/business/break-even/', title: '손익분기점 계산기',
    description: '고정비와 단가·단위 변동비로 손익분기 판매 수량을 계산합니다.', lastReviewed: '2026-09-17', relatedSlugs: ['margin', 'business-feasibility'],
    guide: {
      formula: '손익분기 수량 = 올림(고정비 ÷ (판매단가 − 단위 변동비))',
      examples: [{ title: '250개 판매', text: '고정비 100만원, 단가 1만원, 단위 변동비 6천원이면 250개, 매출 250만원이 필요합니다.' }, { title: '분기점 도달 불가', text: '단가와 단위 변동비가 모두 1만원이면 판매당 기여이익이 없어 도달 불가를 표시합니다.' }],
      limitations: ['모든 제품이 같은 단가·변동비를 가진 예상 시나리오입니다. 수량은 정수로 올림합니다.', '단가가 단위 변동비 이하이면 도달 불가로 표시합니다. 고정비의 기간과 판매 목표 기간을 맞추세요.'],
      sources: [{ label: 'OpenStax 관리회계 · 단일 제품 손익분기점', href: 'https://openstax.org/books/principles-managerial-accounting/pages/3-2-calculate-a-break-even-point-in-units-and-dollars' }],
    },
  },
  {
    slug: 'sales-commission', category: 'business', route: '/business/sales-commission/', title: '판매 수수료 계산기',
    description: '입력한 플랫폼·결제 수수료율과 배송비를 매출에서 차감합니다.', lastReviewed: '2026-09-17', relatedSlugs: ['online-market-settlement', 'margin'],
    guide: {
      formula: '정산액 = 총매출 − 총매출 × (플랫폼 요율 + 결제 요율) ÷ 100 − 배송비',
      examples: [{ title: '수수료와 배송비', text: '매출 100만원, 임의 플랫폼 요율 10%, 결제 2%, 배송비 3만원이면 예상 정산액 85만원입니다.' }, { title: '수수료 없는 거래', text: '매출 10만원, 두 요율 0%, 배송비 5천원이면 9만5천원입니다.' }],
      limitations: ['요율을 직접 입력한 예상 정산액입니다. 두 요율 모두 총매출에 적용합니다.', '수수료 부가세·최저 수수료·반품·원가·세금은 자동 반영하지 않습니다. 실제 계약과 대조하세요.'],
      sources: [{ label: '소상공인24 · 사업 운영 정보 참고', href: 'https://www.sbiz24.kr/' }],
    },
  },
  {
    slug: 'online-market-settlement', category: 'business', route: '/business/online-market-settlement/', title: '온라인 판매 정산 계산기',
    description: '총매출에서 직접 설정한 수수료·배송비·반품액을 차감해 예상 정산액을 봅니다.', lastReviewed: '2026-09-17', relatedSlugs: ['sales-commission', 'monthly-profit-loss'],
    guide: {
      formula: '정산액 = 총매출 − 총매출 기준 플랫폼·결제 수수료 − 배송비 − 반품액',
      examples: [{ title: '반품 포함 정산', text: '매출 100만원, 임의 요율 10%와 2%, 배송 3만원, 반품 5만원이면 80만원입니다.' }, { title: '반품 없는 정산', text: '같은 조건에서 반품 0원이면 85만원입니다.' }],
      limitations: ['입력 요율 기준 예상값으로 특정 플랫폼 정산 규칙을 재현하지 않습니다.', '수수료는 반품 차감 전 총매출에 적용하며 수수료 환급·정산 보류·원가·세금은 제외됩니다.'],
      sources: [{ label: '소상공인24 · 온라인 사업 운영 참고', href: 'https://www.sbiz24.kr/' }],
    },
  },
  {
    slug: 'freelancer-net-income', category: 'business', route: '/business/freelancer-net-income/', title: '프리랜서 순수입 계산기',
    description: '총수입에 직접 입력한 원천징수율을 적용하고 지출 경비를 차감합니다.', lastReviewed: '2026-09-17', relatedSlugs: ['monthly-profit-loss', 'vat'],
    guide: {
      formula: '예상 순수입 = 총수입 − 총수입 × 입력 원천징수율 ÷ 100 − 지출 경비',
      examples: [{ title: '원천징수와 경비', text: '총수입 100만원, 임의 원천징수율 3%, 경비 20만원이면 예상 순수입 77만원입니다.' }, { title: '경비가 큰 달', text: '총수입 100만원, 원천징수율 0%, 경비 120만원이면 예상 순수입 −20만원입니다.' }],
      limitations: ['수동 요율에 따른 현금흐름 예상값입니다. 원천징수는 경비 차감 전 총수입에 적용합니다.', '종합소득세 확정액·필요경비 인정·부가세·보험료·환급 여부는 판단하지 않습니다.'],
      sources: [{ label: '국세청 · 원천징수 및 종합소득세 안내', href: 'https://www.nts.go.kr/' }],
    },
  },
  {
    slug: 'monthly-profit-loss', category: 'business', route: '/business/monthly-profit-loss/', title: '월 손익 계산기',
    description: '월 매출에서 고정비와 변동비 합계를 빼 예상 월 이익 또는 손실을 계산합니다.', lastReviewed: '2026-09-17', relatedSlugs: ['business-feasibility', 'break-even'],
    guide: {
      formula: '월 손익 = 월 매출 − 월 고정비 − 월 변동비',
      examples: [{ title: '흑자 시나리오', text: '월 매출 100만원, 고정비 30만원, 변동비 20만원이면 예상 이익 50만원입니다.' }, { title: '적자 시나리오', text: '월 매출 100만원, 고정비 30만원, 변동비 80만원이면 예상 손실 10만원입니다.' }],
      limitations: ['입력 비용만 반영한 예상 손익이며 회계상 당기순이익이 아닙니다.', '감가상각·세금·대표자 인건비 등 필요한 비용은 직접 합산하고 중복 입력하지 마세요.'],
      sources: [{ label: 'OpenStax 관리회계 · 원가와 이익 분석', href: 'https://openstax.org/details/books/principles-managerial-accounting' }],
    },
  },
  {
    slug: 'business-feasibility', category: 'business', route: '/business/business-feasibility/', title: '사업성 간단 계산기',
    description: '초기 투자와 일정한 월 손익 가정으로 단순 투자금 회수 기간을 추정합니다.', lastReviewed: '2026-09-17', relatedSlugs: ['monthly-profit-loss', 'break-even'],
    guide: {
      formula: '단순 회수 개월 수 = 초기 투자금 ÷ (월 매출 − 월 고정비 − 월 변동비)',
      examples: [{ title: '두 달 회수 가정', text: '초기 투자 100만원, 월 매출 100만원, 고정비 30만원, 변동비 20만원이면 월 이익 50만원으로 2개월입니다.' }, { title: '손실 지속 가정', text: '월 매출 100만원, 고정비 30만원, 변동비 80만원이면 매월 손실이므로 회수 불가를 표시합니다.' }],
      limitations: ['월 이익이 일정하고 전부 투자 회수에 사용된다는 예상값으로 사업 성공을 판단하지 않습니다.', '월 이익이 0 이하이면 회수 불가입니다. 할인율·성장률·추가 투자·세금·운전자금은 반영하지 않습니다.'],
      sources: [{ label: 'OpenStax 관리회계 · 투자 회수 기간', href: 'https://openstax.org/books/principles-managerial-accounting/pages/11-2-evaluate-the-payback-and-accounting-rate-of-return-in-capital-investment-decisions' }],
    },
  },
  {
    slug: 'discount-rate', category: 'business', route: '/business/discount-rate/', title: '할인율 계산기',
    description: '정가와 할인 판매가로 할인 금액과 정가 대비 할인율을 계산합니다.', lastReviewed: '2026-09-17', relatedSlugs: ['margin', 'markup'],
    guide: {
      formula: '할인율 = (정가 − 할인가) ÷ 정가 × 100',
      examples: [{ title: '20% 할인', text: '정가 10만원, 할인가 8만원이면 할인액 2만원, 할인율 20%입니다.' }, { title: '반값 할인', text: '정가 4만원, 할인가 2만원이면 할인액 2만원, 할인율 50%입니다.' }],
      limitations: ['입력 가격을 기준으로 산출한 예상 비교값입니다. 정가는 0원 초과, 할인가는 정가 이하여야 합니다.', '쿠폰·배송비·적립금·중복 할인은 자동 적용하지 않습니다. 비교 가격의 세금 포함 조건을 맞추세요.'],
      sources: [{ label: '한국소비자원 · 가격 비교 참고', href: 'https://www.kca.go.kr/' }],
    },
  },
] as const satisfies ReadonlyArray<CalculatorCatalogEntry>;
